# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: casaos
before:
  hooks:
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - go test -race -v ./...

builds:
  - id: casaos-amd64
    binary: build/sysroot/usr/bin/casaos
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/KaySar12/NextZenOS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/KaySar12/NextZenOS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/KaySar12/NextZenOS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/KaySar12/NextZenOS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/KaySar12/NextZenOS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/KaySar12/NextZenOS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-arm64
    binary: build/sysroot/usr/bin/casaos
    # hooks:
    #   post:
    #     - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/KaySar12/NextZenOS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/KaySar12/NextZenOS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/KaySar12/NextZenOS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/KaySar12/NextZenOS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/KaySar12/NextZenOS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/KaySar12/NextZenOS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-arm-7
    binary: build/sysroot/usr/bin/casaos
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/KaySar12/NextZenOS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/KaySar12/NextZenOS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/KaySar12/NextZenOS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/KaySar12/NextZenOS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/KaySar12/NextZenOS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/KaySar12/NextZenOS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
# release:
#   github:
#     owner: IceWhaleTech
#     name: CasaOS
#   draft: true
#   prerelease: auto
#   mode: replace
#   name_template: "v{{ .Version }}"
release:
  github:
    owner: KaySar12
    name: NextZenOS
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
